#ifndef MLD_CONFIG_H
#define MLD_CONFIG_H

#define MLD_VERSION 0.1.0

#include <string>

/*
 * AUTO-GENERATION WARNING:
 *     This file has been automatically generated from "config.h.in".
 *     DO NOT edit this file, as any changes will be automatically discarded.
*/

namespace mld {

std::wstring kRESOURCES_DIR = L"/Users/kikohs/work/pro/mld/resources/";

} // end namespace mld

#endif // MLD_CONFIG_H
